name: Publish Python distributions to TestPyPI

on:
  push:
#    branches:
#      - develop
#      - feature/github_action
    tags:
      - v*rc
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build-n-publish-pre-release:
    name: Build and publish Python distributions to TestPyPI
    runs-on: ubuntu-18.04
    env:
      PBR_VERSION: v0.0.1rc
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pypa/build
        run: python -m pip install build wheel pbr --user
      - name: Print PBR_VERSION
        run: echo "PBR_VERSION=$PBR_VERSION"
      - name: Print version
        run: python setup.py --version
      - name: Git tag
        run: git tag -l
#      - name: Build a binary wheel and a source tarball
#        run: PBR_VERSION=$(git describe --tags) ; echo "PBR_VERSION=$(PBR_VERSION)" ; python setup.py bdist_wheel sdist
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
#  build-n-publish-release:
#    name: Build and publish Python distributions to PyPI and TestPyPI
#    runs-on: ubuntu-18.04
#    steps:
#      - uses: actions/checkout@master
#      - name: Set up Python 3.7
#        uses: actions/setup-python@v1
#        with:
#          python-version: 3.7
#      - name: Install pypa/build
#        run: python -m pip install build --user
#      - name: Build a binary wheel and a source tarball
#        run: python -m build --sdist --wheel --outdir dist/
#      - name: Publish distribution to PyPI
#        if: startsWith(github.ref, 'refs/tags')
#        uses: pypa/gh-action-pypi-publish@master
#        with:
#          password: ${{ secrets.PYPI_API_TOKEN }}
